languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
colorscheme = 'dark'

theme = "almeida-cv"
#disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://adahlen.ninja"
title = "Alex Dahlen | ADahlen Techs"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#BD5D38"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#BD5D38"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#BD5D38"
pages = 1
swapColumns = true