languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true
colorscheme = 'dark'

theme = "almeida-cv"
#disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://adahlen.ninja"
title = "Alex Dahlen | ADahlen Techs"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#FAFAF8"
colorDark = "#2C2C2C"
colorPageBackground = "#E8E6E1"
colorPrimary = "#C4622D"
colorSecondary = "#7A7570"
colorIconPrimary = "#FAFAF8"
colorIconBackground = "#C4622D"
colorRightColumnBackground = "#2C2C2C"
colorRightColumnHeadingText = "#FAFAF8"
colorRightColumnBodyText = "#C8C4BC"
colorRightColumnIconPrimary = "#2C2C2C"
colorRightColumnIconBackground = "#C4622D"
pages = 1
swapColumns = true
